### ISSUE TITLE
Create initial HTML markup

### ISSUE THREAD

**Issue by a-breezy** [a-breezy/LetsEat#1]
Write skeleton of HTML page.
- [x] link to yelp cdn: https://www.yelp.com/developers/documentation/v3/business_search
- [x] link to jquery cdn: https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js documentation: https://api.jquery.com/
- [x] link to bulma cdn

**Comment by ndmtuan** [comment]
i can work on the issue, pls sent to me
